### ISSUE TITLE
Missing autoload.php

### ISSUE THREAD

**Issue by Metric-nz** [daigo75/vanilla-cron#1]
When I attempt to enable the plugin it throws an error.

With debug enabled I see:

Warning:  Uncaught exception 'Gdn_ErrorException' with message 'require_once(/var/www/forum.thebrandxmethod.com/html/plugins/CronJobs/vendor/autoload.php): failed to open stream: No such file or directory' in /var/www/forum.thebrandxmethod.com/html/plugins/CronJobs/class.cronjobs.plugin.php:9
Stack trace:
#0 /var/www/forum.thebrandxmethod.com/html/plugins/CronJobs/class.cronjobs.plugin.php(9): Gdn_ErrorHandler(2, 'require_once(/v...', '/var/www/forum....', 9, Array)
#1 /var/www/forum.thebrandxmethod.com/html/plugins/CronJobs/class.cronjobs.plugin.php(9): require_once()
#2 /var/www/forum.thebrandxmethod.com/html/library/core/class.pluginmanager.php(286): include_once('/var/www/forum....')
#3 /var/www/forum.thebrandxmethod.com/html/library/core/class.pluginmanager.php(1105): Gdn_PluginManager->IncludePlugins(Array)
#4 /var/www/forum.thebrandxmethod.com/html/library/core/class.pluginmanager.php(976): Gdn_PluginManager->_PluginHook('CronJobs', 1, false)
#5 /var/www/forum.thebrandxmethod.com/html/applications/dashboard/cont in /var/www/forum.thebrandxmethod.com/html/plugins/CronJobs/class.cronjobs.plugin.php on line 9

Fatal error:  main(): Failed opening required '/var/www/forum.thebrandxmethod.com/html/plugins/CronJobs/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/forum.thebrandxmethod.com/html/plugins/CronJobs/class.cronjobs.plugin.php on line 9

There is no vendor directory and therefore no autoload.php

**Comment by daigo75** [comment]
That is correct. The Github repository does not include the vendor directory, you will have to generate it yourself using Composer the repository is used for development and contributions, rather than distribution)

For more information, see https://getcomposer.org/doc/00-intro.md.

--- Original Message ---

**Comment by Metric-nz** [comment]
Fair enough.

Can you point me at a location where I can download  a copy that contains the autoload.php?
I'm finally installing what I now realise is your post scheduler plugin and this is one of the dependencies.The download at http://vanillaforums.org/addon/966 is also missing the vendor directory and I can't see it as a download on the aelia site either.

You were kind enough to send me a copy of post scheduler when I first enquired about this some months ago and I've just paid for it as I'm about to put it into production. I just need this plugin working. Happy to switch to another form of communications, just tell me what I should be using. If I'd realised that you were the developer I was already talking to I wouldn't have created an issue.

Craig Massey

**Comment by daigo75** [comment]
That's odd, the Cron plugin on the Vanilla repository should be fully packaged. I will have to check that.

--- Original Message ---

**Comment by daigo75** [comment]
Cron plugin updated on the Vanilla Forums repository, this time including the _vendor_ folder.
